name: Simple PR Syntax Check for html,css,js and json

on:
  pull_request:

jobs:
  check-syntax-of-html-css-js-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check HTML
        run: npx html-validate --rule "close-order:error" --rule "parser-error:error" "**/*.html"

      - name: Check CSS
        run: npx stylelint "**/*.css" --allow-empty-input

      - name: Check JS
        run: npx terser "**/*.js" --parse

      - name: Check Firebase JSON
        run: npx jsonlint "**/*.json" --quiet
